# Generated by Django 4.2 on 2023-04-13 10:35

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmodel',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='description_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='projectcategorymodel',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название категории'),
        ),
        migrations.AddField(
            model_name='projectcategorymodel',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название категории'),
        ),
        migrations.AddField(
            model_name='projectcategorymodel',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Название категории'),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='client_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='client_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='client_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание проекта'),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание проекта'),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='description_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание проекта'),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название проекта'),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название проекта'),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Название проекта'),
        ),
        migrations.AddField(
            model_name='servicemodel',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание услуги'),
        ),
        migrations.AddField(
            model_name='servicemodel',
            name='description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание услуги'),
        ),
        migrations.AddField(
            model_name='servicemodel',
            name='description_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание услуги'),
        ),
        migrations.AddField(
            model_name='servicemodel',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название услуги'),
        ),
        migrations.AddField(
            model_name='servicemodel',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название услуги'),
        ),
        migrations.AddField(
            model_name='servicemodel',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Название услуги'),
        ),
    ]
