# Generated by Django 4.2 on 2023-04-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_blockmodel_description_en_blockmodel_description_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannermodel',
            name='name',
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
    ]
