# Generated by Django 4.2 on 2023-04-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_bannermodel_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmodel',
            name='views',
            field=models.BigIntegerField(default=0, verbose_name='Просмотры'),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='service',
            field=models.ManyToManyField(blank=True, to='api.servicemodel', verbose_name='Услуга'),
        ),
    ]
