# Generated by Django 4.2 on 2023-04-16 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_newsmodel_views_projectmodel_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannermodel',
            name='image',
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='image_desktop',
            field=models.ImageField(default='', upload_to='banners', verbose_name='Изображение для десктопа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='image_mobile',
            field=models.ImageField(default='', upload_to='banners', verbose_name='Изображение для мобильных'),
            preserve_default=False,
        ),
    ]
