# Generated by Django 4.2 on 2023-04-17 10:06

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_bannermodel_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicemodel',
            name='icon',
            field=models.FileField(blank=True, help_text='Рекомендуемый размер 64x64', null=True, upload_to='services', validators=[api.models.validate_file_extension], verbose_name='Иконка услуги'),
        ),
    ]
