# Generated by Django 4.2 on 2023-04-19 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_aboutusmodel_description_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutusmodel',
            old_name='description_uz',
            new_name='description_zh',
        ),
        migrations.RenameField(
            model_name='aboutusmodel',
            old_name='title_uz',
            new_name='title_zh',
        ),
        migrations.RenameField(
            model_name='bannermodel',
            old_name='image_uz',
            new_name='image_zh',
        ),
        migrations.RenameField(
            model_name='blockmodel',
            old_name='description_uz',
            new_name='description_zh',
        ),
        migrations.RenameField(
            model_name='blockmodel',
            old_name='title_uz',
            new_name='title_zh',
        ),
        migrations.RenameField(
            model_name='consultmodel',
            old_name='description_uz',
            new_name='description_zh',
        ),
        migrations.RenameField(
            model_name='consultmodel',
            old_name='title_uz',
            new_name='title_zh',
        ),
        migrations.RenameField(
            model_name='footermodel',
            old_name='text_uz',
            new_name='text_zh',
        ),
        migrations.RenameField(
            model_name='newsmodel',
            old_name='description_uz',
            new_name='description_zh',
        ),
        migrations.RenameField(
            model_name='newsmodel',
            old_name='title_uz',
            new_name='title_zh',
        ),
        migrations.RenameField(
            model_name='projectcategorymodel',
            old_name='name_uz',
            new_name='name_zh',
        ),
        migrations.RenameField(
            model_name='projectmodel',
            old_name='client_uz',
            new_name='client_zh',
        ),
        migrations.RenameField(
            model_name='projectmodel',
            old_name='description_uz',
            new_name='description_zh',
        ),
        migrations.RenameField(
            model_name='projectmodel',
            old_name='name_uz',
            new_name='name_zh',
        ),
        migrations.RenameField(
            model_name='reviewmodel',
            old_name='description_uz',
            new_name='description_zh',
        ),
        migrations.RenameField(
            model_name='reviewmodel',
            old_name='name_uz',
            new_name='name_zh',
        ),
        migrations.RenameField(
            model_name='reviewmodel',
            old_name='position_uz',
            new_name='position_zh',
        ),
        migrations.RenameField(
            model_name='servicemodel',
            old_name='description_uz',
            new_name='description_zh',
        ),
        migrations.RenameField(
            model_name='servicemodel',
            old_name='name_uz',
            new_name='name_zh',
        ),
    ]
