# Generated by Django 4.2 on 2023-04-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_description_uz_aboutusmodel_description_zh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmodel',
            name='short_description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='short_description_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='short_description_ru',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='short_description_zh',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='short_description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='short_description_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='short_description_ru',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='short_description_zh',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='servicemodel',
            name='short_description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='servicemodel',
            name='short_description_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='servicemodel',
            name='short_description_ru',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='servicemodel',
            name='short_description_zh',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Краткое описание'),
        ),
    ]
