# Generated by Django 4.2 on 2023-04-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_newsmodel_short_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmodel',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Сообщение'),
        ),
    ]
